-   id: blackref
    name: blackref
    description: 'Blackref: The uncompromising BibTeX-file formatter'
    entry: blackref
    language: python
    language_version: python3
    require_serial: true
    types: [text]
    files: '.*bib'
