repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v3.20.0
  hooks:
  - id: pyupgrade
    args: ['--py312-plus']
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-toml
    - id: check-xml
    - id: check-vcs-permalinks
    - id: check-xml
    - id: check-yaml
    - id: debug-statements
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: forbid-new-submodules
    - id: mixed-line-ending
      args: ['--fix', 'lf']
    - id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.1
  hooks:
    - id: ruff
      args: ["--fix", "--ignore=F841"]
    - id: ruff-format
- repo: https://github.com/pycqa/flake8
  rev: "7.3.0"
  hooks:
    - id: flake8
      language_version: python3.12
      additional_dependencies:
        - flake8-executable
        - flake8-bandit
        - flake8-bugbear
        - flake8-pathlib
        - flake8-super-call
        - flake8-debugger
        - flake8-comprehensions
        - flake8-breakpoint
        - flake8-print
        - flake8-todos
        - flake8-2020
        - flake8-mutable
        - flake8-clean-block
      args: ['--select=WT', "--ignore=WT4"]

- repo: 'https://github.com/lovesegfault/beautysh'
  rev: v6.2.1
  hooks:
    - id: beautysh
- repo: 'https://github.com/detailyang/pre-commit-shell'
  rev: 1.0.5
  hooks:
    - id: shell-lint
      args:
        - '--format=json'
- repo: https://github.com/hukkin/mdformat
  rev: 0.7.22
  hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black

#~ - repo: https://github.com/pre-commit/mirrors-mypy
  #~ rev: v1.16.1
  #~ hooks:
    #~ - id: mypy
      #~ exclude: ^tests/
      #~ additional_dependencies:
        #~ - types-click
        #~ - types-tqdm
        #~ - types-colorama
      #~ args: [
        #~ --ignore-missing-imports,
        #~ --install-types,
        #~ --non-interactive,
        #~ --python-version=3.12,
        #~ --warn-unused-configs,
        #~ --warn-unused-ignores,
        #~ --warn-redundant-casts,
        #~ --warn-unreachable,
        #~ --show-error-codes,
        #~ --disallow-incomplete-defs,
        #~ --strict-equality,
        #~ --strict-bytes,
        #~ --report-deprecated-as-note,
        #~ --extra-checks,
        #~ --check-untyped-defs,
        #~ --disallow-untyped-defs
      #~ ]
