repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-ast
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: check-xml
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
        args: ['--autofix']

-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [
            flake8-breakpoint,
            flake8-broken-line,
            flake8-bugbear,
            flake8-builtins,
            flake8-class-newline,
            flake8-comprehensions,
            flake8-debugger,
            flake8-eradicate,
            flake8-if-expr,
            flake8-fixme,
            flake8-markdown,
            pep8-naming]
        args: ['--max-line-length=160', '--ignore=E801,E402,E501,E116,E265,E203,W503,N806,E800,N812,N816']

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.1
    hooks:
    -   id: pyupgrade
        args: ['--py39-plus']
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: '24.2.0'
    hooks:
      - id: black
