language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install coverage coveralls codecov
  - pip install -r requirements.txt

script:
  - make ci-test

after_success:
  - coveralls
